### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Albedaia** [glandu2/BTRFdom#1]
hello 
i have problem when i try to enable Addons  Rappelz nx3
i used blender 2.6.4 and 2.7.6
![screenshot 48](https://cloud.githubusercontent.com/assets/5303081/10793521/4cc4dd0a-7da2-11e5-9a65-aa170da852ad.png)

**Comment by glandu2** [comment]
Can you try with the btrfdom.dll available here: https://ci.appveyor.com/project/glandu2/btrfdom/build/artifacts ?

**Comment by Albedaia** [comment]
thank you so much it's work 100% .
